### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### andrewgiessel/basketballcrawler now has a Chat Room on Gitter

@andrewgiessel has just created a chat room. You can visit it here: [https://gitter.im/andrewgiessel/basketballcrawler](https://gitter.im/andrewgiessel/basketballcrawler?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/andrewgiessel/basketballcrawler?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by titipata** [comment]
@andrewgiessel, should we merge gitter chat to the project?

**Comment by andrewgiessel** [comment]
Yes!

**Comment by titipata** [comment]
I don't have a permission to do that :shaved_ice:

**Comment by andrewgiessel** [comment]
Oh, wow, I just read the email, not the PR itself.  It already asked for it! Jeez that's clever.

**Pull request merged**
