### PR TITLE
Added a class for a player, instead of using a dictionary

### PR DESCRIPTION
**Pull request by wilsonchaney**
- Added player.py to store data in Player class
- Added soup_utils.py to avoid co-dependencies, and just for `def getSoupFromURL()`
- Updated `players.json` to contain data from previous PR (height, weight, positions).

### CODE REVIEW

**Comment by wilsonchaney** [comment]
@andrewgiessel Thoughts?

**Comment by andrewgiessel** [comment]
sorry to not respond sooner!  I'll check this out this afternoon.  Might
you link me a ipynb that uses the new API?  That'd be super helpful.

**Comment by wilsonchaney** [comment]
[Here's a basic notebook](https://gist.github.com/wilsonchaney/ea564405b427942c170b) I threw together.

I made sure to preserve all of the game log functionality in [this notebook](https://github.com/andrewgiessel/basketballcrawler/blob/master/basketball_scraper_notebook.ipynb)

**Comment by andrewgiessel** [comment]
Looks great!  Thanks for the notebook!  I'll merge this.  Would you be
interested in turning these notebooks into an "official" one in another PR
after cleaning it up a bit?

**Comment by wilsonchaney** [comment]
Yep! I'm going to be busy this coming weekend but I'll put a more comprehensive notebook together next week.

**Pull request merged**
